"""Map a repo-relative source path to its file kind and master/family.

Pure string logic. The authoritative glyph *name* comes from the glif body (parsed
elsewhere), not the filename, because UFO filenames use name-mangling.
"""

from __future__ import annotations

import re

from ufo_tdkit_report.model import FileKind

_UFO_RE = re.compile(r"(?P<master>[^/]+)\.ufo/")


def master_of(path: str) -> str | None:
    """Return the ``<Master>`` from ``.../<Master>.ufo/...`` or None."""
    m = _UFO_RE.search(path)
    return m.group("master") if m else None


# Dependency lock files: generated by a package manager, never a font source, and large
# enough that "uv.lock updated" crowds a commit message about outlines. Matched by exact
# basename; anything else a repo wants left out is marked `linguist-generated` in its own
# .gitattributes, which keeps the decision in the repository and the report byte-stable.
LOCK_FILES = frozenset({
    "Cargo.lock",
    "Gemfile.lock",
    "Pipfile.lock",
    "bun.lock",
    "bun.lockb",
    "composer.lock",
    "flake.lock",
    "npm-shrinkwrap.json",
    "package-lock.json",
    "pdm.lock",
    "pixi.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "uv.lock",
    "yarn.lock",
})


def is_lock_file(path: str) -> bool:
    """True for a dependency lock file, wherever it sits in the repo."""
    return path.rsplit("/", 1)[-1] in LOCK_FILES


def classify_path(path: str) -> FileKind | None:
    """Classify a changed file into a report FileKind, or None if irrelevant."""
    lower = path.lower()
    if lower.endswith(".glif"):
        return FileKind.GLIF
    if lower.endswith("kerning.plist"):
        return FileKind.KERNING
    if lower.endswith("groups.plist"):
        return FileKind.GROUPS
    if lower.endswith("fontinfo.plist"):
        return FileKind.FONTINFO
    if lower.endswith(".fea"):
        return FileKind.FEATURES
    if lower.endswith((".designspace", ".dssketch")):  # the same document, two notations
        return FileKind.DESIGNSPACE
    if lower.endswith((".yaml", ".yml")):
        return FileKind.PROFILE
    return None
