"""Render source-change reports as Markdown.

Output follows the conventions of the per-repo release-notes template so these
notes drop into the same release pipeline: an ``## Source changes: from -> to``
title, themed ``###`` sections, bullet lists, and (via the narrator) an AI
narrative over a ``<details>`` technical block. This is the source-side report —
its sections cover outlines, spacing, features, designspace, metadata, and the
build profile — complementary to the binary release diff's coverage/table sections.
"""

from __future__ import annotations

from ufo_tdkit_report.model import FileKind, RangeReport, SourceReport

# FileKind -> human section heading, and the order sections appear in.
_SECTION_FOR_KIND: dict[FileKind, str] = {
    FileKind.GLIF: "Outlines & glyphs",
    FileKind.KERNING: "Spacing & kerning",
    FileKind.GROUPS: "Spacing & kerning",
    FileKind.FEATURES: "OpenType features",
    FileKind.DESIGNSPACE: "Designspace",
    FileKind.FONTINFO: "Metadata",
    FileKind.PROFILE: "Build profile",
    FileKind.OTHER: "Other files",
}
_SECTION_ORDER: list[str] = [
    "Outlines & glyphs",
    "Spacing & kerning",
    "OpenType features",
    "Designspace",
    "Metadata",
    "Build profile",
    "Other files",
]


def _split_spec(spec: str) -> tuple[str, str]:
    """Render a commit spec as ``from -> to`` endpoints."""
    if ".." in spec:
        base, _, head = spec.partition("..")
        return (base or "HEAD~1", head or "HEAD")
    return (f"{spec}~1", spec)


def _render_facts(folded_facts) -> list[str]:
    """Group folded facts into ordered ``### {section}`` Markdown blocks."""
    by_section: dict[str, list[str]] = {}
    for folded in folded_facts:
        section = _SECTION_FOR_KIND.get(folded.file_kind, "Other")
        by_section.setdefault(section, []).append(f"- {folded.summary}")

    lines: list[str] = []
    ordered = _SECTION_ORDER + [s for s in by_section if s not in _SECTION_ORDER]
    for section in ordered:
        bullets = by_section.get(section)
        if not bullets:
            continue
        lines.append("")
        lines.append(f"### {section}")
        lines.extend(bullets)
    return lines


def _credit(ai: bool = False, model: str | None = None, provider: str | None = None) -> str:
    """Bare credit text: tool + version (+ AI provider/model when narrated). No markup.

    The provider is named alongside the model because with several providers reachable,
    the model id alone no longer identifies what actually produced the prose — and an
    AI-drafted note has to stay auditable.
    """
    from ufo_tdkit_report import __version__

    text = f"Generated by tdreport {__version__}"
    if ai:
        stamp = f"{provider}/{model}" if provider and model else (model or "")
        text += f" with AI narration, model: {stamp}" if stamp else " with AI narration"
    return text


def attribution(ai: bool = False, model: str | None = None, provider: str | None = None) -> str:
    """Markdown footer line for reports (italic)."""
    return f"_{_credit(ai, model, provider)}._"


def _with_footer(lines: list[str], footer: bool) -> str:
    """Join report lines, appending the attribution footer unless suppressed."""
    if footer:
        lines = [*lines, "", "---", attribution()]
    return "\n".join(lines)


def render_report(report: SourceReport, *, footer: bool = True) -> str:
    base, head = _split_spec(report.commit_spec)
    lines: list[str] = [f"## Source changes: {base} → {head}"]
    if report.profile_name:
        lines.append(f"*Built with profile `{report.profile_name}`.*")
    lines.append(
        f"*{report.changed_file_count} changed files → {report.raw_fact_count} facts "
        f"→ {len(report.folded_facts)} after folding.*"
    )

    if not report.folded_facts:
        lines.append("")
        lines.append("_No semantic source changes (binary-diff territory only)._")
        return _with_footer(lines, footer)

    lines.extend(_render_facts(report.folded_facts))
    return _with_footer(lines, footer)


def _commit_subject(folded_facts) -> str:
    """A one-line commit subject synthesized from the folded facts."""
    if not folded_facts:
        return "No source changes"
    summaries = [f.summary for f in folded_facts]
    head = summaries[:2]
    overflow = len(summaries) - len(head)
    subject = "; ".join(head)
    if overflow:
        subject += f" (+{overflow} more)"
    # Keep subjects reasonable for a commit line.
    return subject if len(subject) <= 72 else subject[:69] + "…"


def render_commit_message(report: SourceReport) -> str:
    """Render facts as a commit message: subject line, blank, then grouped fact bullets."""
    lines: list[str] = [_commit_subject(report.folded_facts)]
    if not report.folded_facts:
        return lines[0] + "\n"

    lines.append("")
    by_section: dict[str, list[str]] = {}
    for folded in report.folded_facts:
        section = _SECTION_FOR_KIND.get(folded.file_kind, "Other")
        by_section.setdefault(section, []).append(f"- {folded.summary}")
    ordered = _SECTION_ORDER + [s for s in by_section if s not in _SECTION_ORDER]
    for section in ordered:
        bullets = by_section.get(section)
        if not bullets:
            continue
        lines.append(f"{section}:")
        lines.extend(bullets)
    # Plain trailer (not markdown) so it sits cleanly in the git commit message.
    lines.append("")
    lines.append(_credit())
    return "\n".join(lines) + "\n"


def render_range_report(report: RangeReport, *, footer: bool = True) -> str:
    base, head = _split_spec(report.range_spec)
    lines: list[str] = [f"## Source changes: {base} → {head}"]
    if report.profile_name:
        lines.append(f"*Built with profile `{report.profile_name}`.*")
    netted = f" ({report.net_removed_count} netted out)" if report.net_removed_count else ""
    lines.append(f"*{report.commit_count} commits, {len(report.folded_facts)} facts{netted}.*")

    if report.commits:
        lines.append("")
        lines.append("### Commits")
        for sha, subject in report.commits:
            lines.append(f"- `{sha[:7]}` {subject}")

    if not report.folded_facts:
        lines.append("")
        lines.append("_No semantic source changes across the range (binary-diff territory only)._")
        return _with_footer(lines, footer)

    lines.extend(_render_facts(report.folded_facts))
    return _with_footer(lines, footer)
